/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

export interface MessageResponse {
  message: string;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  customer: "customer",
  service_provider: "service_provider",
} as const;

export interface User {
  id: number;
  email: string;
  name: string;
  phone?: string | null;
  address?: string | null;
  role: UserRole;
  avatarUrl?: string | null;
  createdAt: string;
}

export type SignUpRequestRole =
  (typeof SignUpRequestRole)[keyof typeof SignUpRequestRole];

export const SignUpRequestRole = {
  customer: "customer",
  service_provider: "service_provider",
} as const;

export interface SignUpRequest {
  email: string;
  /** @minLength 6 */
  password: string;
  name: string;
  phone?: string | null;
  role: SignUpRequestRole;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SendOtpRequest {
  email: string;
}

export interface VerifyOtpRequest {
  email: string;
  otp: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface Service {
  id: number;
  name: string;
  description: string;
  category: string;
  basePrice: number;
  imageUrl?: string | null;
  providerId: number;
  providerName: string;
  providerRating?: number | null;
  availabilityStatus: boolean;
  totalReviews: number;
  createdAt: string;
}

export interface ServicesResponse {
  services: Service[];
  total: number;
  page: number;
  limit: number;
}

export interface CreateServiceRequest {
  name: string;
  description: string;
  category: string;
  basePrice: number;
  imageUrl?: string | null;
  availabilityStatus?: boolean;
}

export interface UpdateServiceRequest {
  name?: string;
  description?: string;
  category?: string;
  basePrice?: number;
  imageUrl?: string | null;
  availabilityStatus?: boolean;
}

export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];

export const BookingStatus = {
  pending: "pending",
  confirmed: "confirmed",
  in_progress: "in_progress",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export interface Booking {
  id: number;
  customerId: number;
  customerName: string;
  serviceId: number;
  serviceName: string;
  serviceCategory: string;
  providerId: number;
  providerName: string;
  bookingDate: string;
  timeSlot: string;
  location: string;
  notes?: string | null;
  status: BookingStatus;
  totalPrice: number;
  hasReview: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface BookingsResponse {
  bookings: Booking[];
  total: number;
}

export interface CreateBookingRequest {
  serviceId: number;
  bookingDate: string;
  timeSlot: string;
  location: string;
  notes?: string | null;
}

export type UpdateBookingStatusRequestStatus =
  (typeof UpdateBookingStatusRequestStatus)[keyof typeof UpdateBookingStatusRequestStatus];

export const UpdateBookingStatusRequestStatus = {
  pending: "pending",
  confirmed: "confirmed",
  in_progress: "in_progress",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export interface UpdateBookingStatusRequest {
  status: UpdateBookingStatusRequestStatus;
}

export interface AvailabilitySlot {
  id: number;
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  isAvailable: boolean;
}

export interface AvailabilityResponse {
  schedule: AvailabilitySlot[];
}

export type UpdateAvailabilityRequestScheduleItem = {
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  isAvailable: boolean;
};

export interface UpdateAvailabilityRequest {
  schedule: UpdateAvailabilityRequestScheduleItem[];
}

export interface ProviderStats {
  totalEarnings: number;
  totalBookings: number;
  completedBookings: number;
  pendingBookings: number;
  averageRating?: number | null;
  totalReviews: number;
}

export interface CustomerStats {
  totalBookings: number;
  completedBookings: number;
  pendingBookings: number;
  totalSpent: number;
}

export interface UpdateProfileRequest {
  name?: string;
  phone?: string | null;
  address?: string | null;
}

export interface Review {
  id: number;
  bookingId: number;
  customerId: number;
  customerName: string;
  providerId: number;
  serviceId: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  reviewText?: string | null;
  createdAt: string;
}

export interface ReviewsResponse {
  reviews: Review[];
  averageRating?: number | null;
  total: number;
}

export interface CreateReviewRequest {
  bookingId: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  reviewText?: string | null;
}

export type GetServicesParams = {
  category?: string;
  search?: string;
  page?: number;
  limit?: number;
};

export type GetBookingsParams = {
  status?: GetBookingsStatus;
  role?: GetBookingsRole;
};

export type GetBookingsStatus =
  (typeof GetBookingsStatus)[keyof typeof GetBookingsStatus];

export const GetBookingsStatus = {
  pending: "pending",
  confirmed: "confirmed",
  in_progress: "in_progress",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export type GetBookingsRole =
  (typeof GetBookingsRole)[keyof typeof GetBookingsRole];

export const GetBookingsRole = {
  customer: "customer",
  provider: "provider",
} as const;
