/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Register a new user
 */
export const signUpBodyPasswordMin = 6;

export const SignUpBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(signUpBodyPasswordMin),
  name: zod.string(),
  phone: zod.string().nullish(),
  role: zod.enum(["customer", "service_provider"]),
});

/**
 * @summary Login with email and password
 */
export const LoginBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    email: zod.string(),
    name: zod.string(),
    phone: zod.string().nullish(),
    address: zod.string().nullish(),
    role: zod.enum(["customer", "service_provider"]),
    avatarUrl: zod.string().nullish(),
    createdAt: zod.date(),
  }),
  token: zod.string(),
});

/**
 * @summary Send OTP to email for passwordless login
 */
export const SendOtpBody = zod.object({
  email: zod.string().email(),
});

export const SendOtpResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Verify OTP and login
 */
export const VerifyOtpBody = zod.object({
  email: zod.string().email(),
  otp: zod.string(),
});

export const VerifyOtpResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    email: zod.string(),
    name: zod.string(),
    phone: zod.string().nullish(),
    address: zod.string().nullish(),
    role: zod.enum(["customer", "service_provider"]),
    avatarUrl: zod.string().nullish(),
    createdAt: zod.date(),
  }),
  token: zod.string(),
});

/**
 * @summary Logout
 */
export const LogoutResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  name: zod.string(),
  phone: zod.string().nullish(),
  address: zod.string().nullish(),
  role: zod.enum(["customer", "service_provider"]),
  avatarUrl: zod.string().nullish(),
  createdAt: zod.date(),
});

/**
 * @summary List all available services
 */
export const getServicesQueryPageDefault = 1;
export const getServicesQueryLimitDefault = 20;

export const GetServicesQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
  page: zod.coerce.number().default(getServicesQueryPageDefault),
  limit: zod.coerce.number().default(getServicesQueryLimitDefault),
});

export const GetServicesResponse = zod.object({
  services: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      description: zod.string(),
      category: zod.string(),
      basePrice: zod.number(),
      imageUrl: zod.string().nullish(),
      providerId: zod.number(),
      providerName: zod.string(),
      providerRating: zod.number().nullish(),
      availabilityStatus: zod.boolean(),
      totalReviews: zod.number(),
      createdAt: zod.date(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Create a new service (provider only)
 */
export const CreateServiceBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  basePrice: zod.number(),
  imageUrl: zod.string().nullish(),
  availabilityStatus: zod.boolean().optional(),
});

/**
 * @summary Get a service by ID
 */
export const GetServiceParams = zod.object({
  id: zod.coerce.number(),
});

export const GetServiceResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  basePrice: zod.number(),
  imageUrl: zod.string().nullish(),
  providerId: zod.number(),
  providerName: zod.string(),
  providerRating: zod.number().nullish(),
  availabilityStatus: zod.boolean(),
  totalReviews: zod.number(),
  createdAt: zod.date(),
});

/**
 * @summary Update a service
 */
export const UpdateServiceParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateServiceBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  category: zod.string().optional(),
  basePrice: zod.number().optional(),
  imageUrl: zod.string().nullish(),
  availabilityStatus: zod.boolean().optional(),
});

export const UpdateServiceResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  basePrice: zod.number(),
  imageUrl: zod.string().nullish(),
  providerId: zod.number(),
  providerName: zod.string(),
  providerRating: zod.number().nullish(),
  availabilityStatus: zod.boolean(),
  totalReviews: zod.number(),
  createdAt: zod.date(),
});

/**
 * @summary Get bookings for current user
 */
export const GetBookingsQueryParams = zod.object({
  status: zod
    .enum(["pending", "confirmed", "in_progress", "completed", "cancelled"])
    .optional(),
  role: zod.enum(["customer", "provider"]).optional(),
});

export const GetBookingsResponse = zod.object({
  bookings: zod.array(
    zod.object({
      id: zod.number(),
      customerId: zod.number(),
      customerName: zod.string(),
      serviceId: zod.number(),
      serviceName: zod.string(),
      serviceCategory: zod.string(),
      providerId: zod.number(),
      providerName: zod.string(),
      bookingDate: zod.date(),
      timeSlot: zod.string(),
      location: zod.string(),
      notes: zod.string().nullish(),
      status: zod.enum([
        "pending",
        "confirmed",
        "in_progress",
        "completed",
        "cancelled",
      ]),
      totalPrice: zod.number(),
      hasReview: zod.boolean(),
      createdAt: zod.date(),
      updatedAt: zod.date(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a new booking
 */
export const CreateBookingBody = zod.object({
  serviceId: zod.number(),
  bookingDate: zod.date(),
  timeSlot: zod.string(),
  location: zod.string(),
  notes: zod.string().nullish(),
});

/**
 * @summary Get a booking by ID
 */
export const GetBookingParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBookingResponse = zod.object({
  id: zod.number(),
  customerId: zod.number(),
  customerName: zod.string(),
  serviceId: zod.number(),
  serviceName: zod.string(),
  serviceCategory: zod.string(),
  providerId: zod.number(),
  providerName: zod.string(),
  bookingDate: zod.date(),
  timeSlot: zod.string(),
  location: zod.string(),
  notes: zod.string().nullish(),
  status: zod.enum([
    "pending",
    "confirmed",
    "in_progress",
    "completed",
    "cancelled",
  ]),
  totalPrice: zod.number(),
  hasReview: zod.boolean(),
  createdAt: zod.date(),
  updatedAt: zod.date(),
});

/**
 * @summary Update booking status
 */
export const UpdateBookingStatusParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBookingStatusBody = zod.object({
  status: zod.enum([
    "pending",
    "confirmed",
    "in_progress",
    "completed",
    "cancelled",
  ]),
});

export const UpdateBookingStatusResponse = zod.object({
  id: zod.number(),
  customerId: zod.number(),
  customerName: zod.string(),
  serviceId: zod.number(),
  serviceName: zod.string(),
  serviceCategory: zod.string(),
  providerId: zod.number(),
  providerName: zod.string(),
  bookingDate: zod.date(),
  timeSlot: zod.string(),
  location: zod.string(),
  notes: zod.string().nullish(),
  status: zod.enum([
    "pending",
    "confirmed",
    "in_progress",
    "completed",
    "cancelled",
  ]),
  totalPrice: zod.number(),
  hasReview: zod.boolean(),
  createdAt: zod.date(),
  updatedAt: zod.date(),
});

/**
 * @summary Get provider's availability schedule
 */
export const getMyAvailabilityResponseScheduleItemDayOfWeekMin = 0;
export const getMyAvailabilityResponseScheduleItemDayOfWeekMax = 6;

export const GetMyAvailabilityResponse = zod.object({
  schedule: zod.array(
    zod.object({
      id: zod.number(),
      dayOfWeek: zod
        .number()
        .min(getMyAvailabilityResponseScheduleItemDayOfWeekMin)
        .max(getMyAvailabilityResponseScheduleItemDayOfWeekMax),
      startTime: zod.string(),
      endTime: zod.string(),
      isAvailable: zod.boolean(),
    }),
  ),
});

/**
 * @summary Update provider availability
 */
export const updateAvailabilityBodyScheduleItemDayOfWeekMin = 0;
export const updateAvailabilityBodyScheduleItemDayOfWeekMax = 6;

export const UpdateAvailabilityBody = zod.object({
  schedule: zod.array(
    zod.object({
      dayOfWeek: zod
        .number()
        .min(updateAvailabilityBodyScheduleItemDayOfWeekMin)
        .max(updateAvailabilityBodyScheduleItemDayOfWeekMax),
      startTime: zod.string(),
      endTime: zod.string(),
      isAvailable: zod.boolean(),
    }),
  ),
});

export const updateAvailabilityResponseScheduleItemDayOfWeekMin = 0;
export const updateAvailabilityResponseScheduleItemDayOfWeekMax = 6;

export const UpdateAvailabilityResponse = zod.object({
  schedule: zod.array(
    zod.object({
      id: zod.number(),
      dayOfWeek: zod
        .number()
        .min(updateAvailabilityResponseScheduleItemDayOfWeekMin)
        .max(updateAvailabilityResponseScheduleItemDayOfWeekMax),
      startTime: zod.string(),
      endTime: zod.string(),
      isAvailable: zod.boolean(),
    }),
  ),
});

/**
 * @summary Get a specific provider's availability
 */
export const GetProviderAvailabilityParams = zod.object({
  id: zod.coerce.number(),
});

export const getProviderAvailabilityResponseScheduleItemDayOfWeekMin = 0;
export const getProviderAvailabilityResponseScheduleItemDayOfWeekMax = 6;

export const GetProviderAvailabilityResponse = zod.object({
  schedule: zod.array(
    zod.object({
      id: zod.number(),
      dayOfWeek: zod
        .number()
        .min(getProviderAvailabilityResponseScheduleItemDayOfWeekMin)
        .max(getProviderAvailabilityResponseScheduleItemDayOfWeekMax),
      startTime: zod.string(),
      endTime: zod.string(),
      isAvailable: zod.boolean(),
    }),
  ),
});

/**
 * @summary Get provider dashboard stats
 */
export const GetProviderStatsResponse = zod.object({
  totalEarnings: zod.number(),
  totalBookings: zod.number(),
  completedBookings: zod.number(),
  pendingBookings: zod.number(),
  averageRating: zod.number().nullish(),
  totalReviews: zod.number(),
});

/**
 * @summary Get current user profile
 */
export const GetCurrentUserResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  name: zod.string(),
  phone: zod.string().nullish(),
  address: zod.string().nullish(),
  role: zod.enum(["customer", "service_provider"]),
  avatarUrl: zod.string().nullish(),
  createdAt: zod.date(),
});

/**
 * @summary Update user profile
 */
export const UpdateProfileBody = zod.object({
  name: zod.string().optional(),
  phone: zod.string().nullish(),
  address: zod.string().nullish(),
});

export const UpdateProfileResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  name: zod.string(),
  phone: zod.string().nullish(),
  address: zod.string().nullish(),
  role: zod.enum(["customer", "service_provider"]),
  avatarUrl: zod.string().nullish(),
  createdAt: zod.date(),
});

/**
 * @summary Get customer dashboard stats
 */
export const GetCustomerStatsResponse = zod.object({
  totalBookings: zod.number(),
  completedBookings: zod.number(),
  pendingBookings: zod.number(),
  totalSpent: zod.number(),
});

/**
 * @summary Create a review for a completed booking
 */
export const createReviewBodyRatingMax = 5;

export const CreateReviewBody = zod.object({
  bookingId: zod.number(),
  rating: zod.number().min(1).max(createReviewBodyRatingMax),
  reviewText: zod.string().nullish(),
});

/**
 * @summary Get reviews for a service
 */
export const GetServiceReviewsParams = zod.object({
  serviceId: zod.coerce.number(),
});

export const getServiceReviewsResponseReviewsItemRatingMax = 5;

export const GetServiceReviewsResponse = zod.object({
  reviews: zod.array(
    zod.object({
      id: zod.number(),
      bookingId: zod.number(),
      customerId: zod.number(),
      customerName: zod.string(),
      providerId: zod.number(),
      serviceId: zod.number(),
      rating: zod
        .number()
        .min(1)
        .max(getServiceReviewsResponseReviewsItemRatingMax),
      reviewText: zod.string().nullish(),
      createdAt: zod.date(),
    }),
  ),
  averageRating: zod.number().nullish(),
  total: zod.number(),
});

/**
 * @summary Get reviews for a provider
 */
export const GetProviderReviewsParams = zod.object({
  providerId: zod.coerce.number(),
});

export const getProviderReviewsResponseReviewsItemRatingMax = 5;

export const GetProviderReviewsResponse = zod.object({
  reviews: zod.array(
    zod.object({
      id: zod.number(),
      bookingId: zod.number(),
      customerId: zod.number(),
      customerName: zod.string(),
      providerId: zod.number(),
      serviceId: zod.number(),
      rating: zod
        .number()
        .min(1)
        .max(getProviderReviewsResponseReviewsItemRatingMax),
      reviewText: zod.string().nullish(),
      createdAt: zod.date(),
    }),
  ),
  averageRating: zod.number().nullish(),
  total: zod.number(),
});
