/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { BookingStatus } from "./bookingStatus";

export interface Booking {
  id: number;
  customerId: number;
  customerName: string;
  serviceId: number;
  serviceName: string;
  serviceCategory: string;
  providerId: number;
  providerName: string;
  bookingDate: Date;
  timeSlot: string;
  location: string;
  notes?: string | null;
  status: BookingStatus;
  totalPrice: number;
  hasReview: boolean;
  createdAt: Date;
  updatedAt: Date;
}
