/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */

export interface CustomerStats {
  totalBookings: number;
  completedBookings: number;
  pendingBookings: number;
  totalSpent: number;
}
