/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */

export type GetBookingsRole =
  (typeof GetBookingsRole)[keyof typeof GetBookingsRole];

export const GetBookingsRole = {
  customer: "customer",
  provider: "provider",
} as const;
