/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { GetBookingsRole } from "./getBookingsRole";
import type { GetBookingsStatus } from "./getBookingsStatus";

export type GetBookingsParams = {
  status?: GetBookingsStatus;
  role?: GetBookingsRole;
};
