/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */

export interface Review {
  id: number;
  bookingId: number;
  customerId: number;
  customerName: string;
  providerId: number;
  serviceId: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  reviewText?: string | null;
  createdAt: Date;
}
