/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { Review } from "./review";

export interface ReviewsResponse {
  reviews: Review[];
  averageRating?: number | null;
  total: number;
}
