/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */

export interface Service {
  id: number;
  name: string;
  description: string;
  category: string;
  basePrice: number;
  imageUrl?: string | null;
  providerId: number;
  providerName: string;
  providerRating?: number | null;
  availabilityStatus: boolean;
  totalReviews: number;
  createdAt: Date;
}
