/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { Service } from "./service";

export interface ServicesResponse {
  services: Service[];
  total: number;
  page: number;
  limit: number;
}
