/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { SignUpRequestRole } from "./signUpRequestRole";

export interface SignUpRequest {
  email: string;
  /** @minLength 6 */
  password: string;
  name: string;
  phone?: string | null;
  role: SignUpRequestRole;
}
