/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */

export type UpdateAvailabilityRequestScheduleItem = {
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  isAvailable: boolean;
};
