/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * 24x7 Service App API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";

export interface User {
  id: number;
  email: string;
  name: string;
  phone?: string | null;
  address?: string | null;
  role: UserRole;
  avatarUrl?: string | null;
  createdAt: Date;
}
